version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - ~/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost
      PGADMIN_DEFAULT_PASSWORD: s3cr3t
      PGADMIN_LISTEN_PORT: 5050
    volumes:
       - ~/data/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
